/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantTrackingCreateNewJobOpeningRequest
 */
public class ApplicantTrackingCreateNewJobOpeningRequestTest {
    private final ApplicantTrackingCreateNewJobOpeningRequest model = new ApplicantTrackingCreateNewJobOpeningRequest();

    /**
     * Model tests for ApplicantTrackingCreateNewJobOpeningRequest
     */
    @Test
    public void testApplicantTrackingCreateNewJobOpeningRequest() {
        // TODO: test ApplicantTrackingCreateNewJobOpeningRequest
    }

    /**
     * Test the property 'postingTitle'
     */
    @Test
    public void postingTitleTest() {
        // TODO: test postingTitle
    }

    /**
     * Test the property 'jobStatus'
     */
    @Test
    public void jobStatusTest() {
        // TODO: test jobStatus
    }

    /**
     * Test the property 'hiringLead'
     */
    @Test
    public void hiringLeadTest() {
        // TODO: test hiringLead
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'employmentType'
     */
    @Test
    public void employmentTypeTest() {
        // TODO: test employmentType
    }

    /**
     * Test the property 'minimumExperience'
     */
    @Test
    public void minimumExperienceTest() {
        // TODO: test minimumExperience
    }

    /**
     * Test the property 'compensation'
     */
    @Test
    public void compensationTest() {
        // TODO: test compensation
    }

    /**
     * Test the property 'jobLocation'
     */
    @Test
    public void jobLocationTest() {
        // TODO: test jobLocation
    }

    /**
     * Test the property 'jobDescription'
     */
    @Test
    public void jobDescriptionTest() {
        // TODO: test jobDescription
    }

    /**
     * Test the property 'applicationQuestionResume'
     */
    @Test
    public void applicationQuestionResumeTest() {
        // TODO: test applicationQuestionResume
    }

    /**
     * Test the property 'applicationQuestionAddress'
     */
    @Test
    public void applicationQuestionAddressTest() {
        // TODO: test applicationQuestionAddress
    }

    /**
     * Test the property 'applicationQuestionLinkedinUrl'
     */
    @Test
    public void applicationQuestionLinkedinUrlTest() {
        // TODO: test applicationQuestionLinkedinUrl
    }

    /**
     * Test the property 'applicationQuestionDateAvailable'
     */
    @Test
    public void applicationQuestionDateAvailableTest() {
        // TODO: test applicationQuestionDateAvailable
    }

    /**
     * Test the property 'applicationQuestionDesiredSalary'
     */
    @Test
    public void applicationQuestionDesiredSalaryTest() {
        // TODO: test applicationQuestionDesiredSalary
    }

    /**
     * Test the property 'applicationQuestionCoverLetter'
     */
    @Test
    public void applicationQuestionCoverLetterTest() {
        // TODO: test applicationQuestionCoverLetter
    }

    /**
     * Test the property 'applicationQuestionReferredBy'
     */
    @Test
    public void applicationQuestionReferredByTest() {
        // TODO: test applicationQuestionReferredBy
    }

    /**
     * Test the property 'applicationQuestionWebsiteUrl'
     */
    @Test
    public void applicationQuestionWebsiteUrlTest() {
        // TODO: test applicationQuestionWebsiteUrl
    }

    /**
     * Test the property 'applicationQuestionHighestEducation'
     */
    @Test
    public void applicationQuestionHighestEducationTest() {
        // TODO: test applicationQuestionHighestEducation
    }

    /**
     * Test the property 'applicationQuestionCollege'
     */
    @Test
    public void applicationQuestionCollegeTest() {
        // TODO: test applicationQuestionCollege
    }

    /**
     * Test the property 'applicationQuestionReferences'
     */
    @Test
    public void applicationQuestionReferencesTest() {
        // TODO: test applicationQuestionReferences
    }

    /**
     * Test the property 'internalJobCode'
     */
    @Test
    public void internalJobCodeTest() {
        // TODO: test internalJobCode
    }

}
