/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicantTrackingGetApplicationDetailsResponseApplicantAddress;
import com.konfigthis.client.model.ApplicantTrackingGetApplicationDetailsResponseApplicantEducation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantTrackingGetApplicationDetailsResponseApplicant
 */
public class ApplicantTrackingGetApplicationDetailsResponseApplicantTest {
    private final ApplicantTrackingGetApplicationDetailsResponseApplicant model = new ApplicantTrackingGetApplicationDetailsResponseApplicant();

    /**
     * Model tests for ApplicantTrackingGetApplicationDetailsResponseApplicant
     */
    @Test
    public void testApplicantTrackingGetApplicationDetailsResponseApplicant() {
        // TODO: test ApplicantTrackingGetApplicationDetailsResponseApplicant
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'linkedinUrl'
     */
    @Test
    public void linkedinUrlTest() {
        // TODO: test linkedinUrl
    }

    /**
     * Test the property 'websiteUrl'
     */
    @Test
    public void websiteUrlTest() {
        // TODO: test websiteUrl
    }

    /**
     * Test the property 'availableStartDate'
     */
    @Test
    public void availableStartDateTest() {
        // TODO: test availableStartDate
    }

    /**
     * Test the property 'education'
     */
    @Test
    public void educationTest() {
        // TODO: test education
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    public void avatarTest() {
        // TODO: test avatar
    }

}
