/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BenefitPlan
 */
public class BenefitPlanTest {
    private final BenefitPlan model = new BenefitPlan();

    /**
     * Model tests for BenefitPlan
     */
    @Test
    public void testBenefitPlan() {
        // TODO: test BenefitPlan
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'deductionTypeId'
     */
    @Test
    public void deductionTypeIdTest() {
        // TODO: test deductionTypeId
    }

    /**
     * Test the property 'startYmd'
     */
    @Test
    public void startYmdTest() {
        // TODO: test startYmd
    }

    /**
     * Test the property 'endYmd'
     */
    @Test
    public void endYmdTest() {
        // TODO: test endYmd
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'meetAcaMin'
     */
    @Test
    public void meetAcaMinTest() {
        // TODO: test meetAcaMin
    }

}
