/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BenefitGroupPlan
 */
public class BenefitGroupPlanTest {
    private final BenefitGroupPlan model = new BenefitGroupPlan();

    /**
     * Model tests for BenefitGroupPlan
     */
    @Test
    public void testBenefitGroupPlan() {
        // TODO: test BenefitGroupPlan
    }

    /**
     * Test the property 'benefitGroupId'
     */
    @Test
    public void benefitGroupIdTest() {
        // TODO: test benefitGroupId
    }

    /**
     * Test the property 'benefitPlanId'
     */
    @Test
    public void benefitPlanIdTest() {
        // TODO: test benefitPlanId
    }

    /**
     * Test the property 'eligibility'
     */
    @Test
    public void eligibilityTest() {
        // TODO: test eligibility
    }

    /**
     * Test the property 'waitPeriod'
     */
    @Test
    public void waitPeriodTest() {
        // TODO: test waitPeriod
    }

    /**
     * Test the property 'waitPeriodType'
     */
    @Test
    public void waitPeriodTypeTest() {
        // TODO: test waitPeriodType
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

}
