/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BenefitPlanCoverage
 */
public class BenefitPlanCoverageTest {
    private final BenefitPlanCoverage model = new BenefitPlanCoverage();

    /**
     * Model tests for BenefitPlanCoverage
     */
    @Test
    public void testBenefitPlanCoverage() {
        // TODO: test BenefitPlanCoverage
    }

    /**
     * Test the property 'benefitPlanId'
     */
    @Test
    public void benefitPlanIdTest() {
        // TODO: test benefitPlanId
    }

    /**
     * Test the property 'benefitCoverageId'
     */
    @Test
    public void benefitCoverageIdTest() {
        // TODO: test benefitCoverageId
    }

    /**
     * Test the property 'totalCost'
     */
    @Test
    public void totalCostTest() {
        // TODO: test totalCost
    }

    /**
     * Test the property 'currencyType'
     */
    @Test
    public void currencyTypeTest() {
        // TODO: test currencyType
    }

    /**
     * Test the property 'startYmd'
     */
    @Test
    public void startYmdTest() {
        // TODO: test startYmd
    }

    /**
     * Test the property 'endYmd'
     */
    @Test
    public void endYmdTest() {
        // TODO: test endYmd
    }

}
