/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CompanyBenefitResponse
 */
public class CompanyBenefitResponseTest {
    private final CompanyBenefitResponse model = new CompanyBenefitResponse();

    /**
     * Model tests for CompanyBenefitResponse
     */
    @Test
    public void testCompanyBenefitResponse() {
        // TODO: test CompanyBenefitResponse
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'benefitVendorId'
     */
    @Test
    public void benefitVendorIdTest() {
        // TODO: test benefitVendorId
    }

    /**
     * Test the property 'benefitType'
     */
    @Test
    public void benefitTypeTest() {
        // TODO: test benefitType
    }

    /**
     * Test the property 'deductionTypeId'
     */
    @Test
    public void deductionTypeIdTest() {
        // TODO: test deductionTypeId
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'planUrl'
     */
    @Test
    public void planUrlTest() {
        // TODO: test planUrl
    }

    /**
     * Test the property 'ssoLoginUrl'
     */
    @Test
    public void ssoLoginUrlTest() {
        // TODO: test ssoLoginUrl
    }

    /**
     * Test the property 'ssoLoginUrlLinkText'
     */
    @Test
    public void ssoLoginUrlLinkTextTest() {
        // TODO: test ssoLoginUrlLinkText
    }

    /**
     * Test the property 'safeHarbor'
     */
    @Test
    public void safeHarborTest() {
        // TODO: test safeHarbor
    }

    /**
     * Test the property 'meetAcaMin'
     */
    @Test
    public void meetAcaMinTest() {
        // TODO: test meetAcaMin
    }

    /**
     * Test the property 'reimbursementAmount'
     */
    @Test
    public void reimbursementAmountTest() {
        // TODO: test reimbursementAmount
    }

    /**
     * Test the property 'reimbursementFrequency'
     */
    @Test
    public void reimbursementFrequencyTest() {
        // TODO: test reimbursementFrequency
    }

    /**
     * Test the property 'minEssentialCoverage'
     */
    @Test
    public void minEssentialCoverageTest() {
        // TODO: test minEssentialCoverage
    }

}
