/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmployeePaystubDeductionsInner;
import com.konfigthis.client.model.EmployeePaystubDepositsInner;
import com.konfigthis.client.model.EmployeePaystubTaxesInner;
import com.konfigthis.client.model.EmployeePaystubWagesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeePaystub
 */
public class EmployeePaystubTest {
    private final EmployeePaystub model = new EmployeePaystub();

    /**
     * Model tests for EmployeePaystub
     */
    @Test
    public void testEmployeePaystub() {
        // TODO: test EmployeePaystub
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'externalRecordId'
     */
    @Test
    public void externalRecordIdTest() {
        // TODO: test externalRecordId
    }

    /**
     * Test the property 'payPeriodFrom'
     */
    @Test
    public void payPeriodFromTest() {
        // TODO: test payPeriodFrom
    }

    /**
     * Test the property 'payPeriodTo'
     */
    @Test
    public void payPeriodToTest() {
        // TODO: test payPeriodTo
    }

    /**
     * Test the property 'payDate'
     */
    @Test
    public void payDateTest() {
        // TODO: test payDate
    }

    /**
     * Test the property 'payorName'
     */
    @Test
    public void payorNameTest() {
        // TODO: test payorName
    }

    /**
     * Test the property 'payorAdd1'
     */
    @Test
    public void payorAdd1Test() {
        // TODO: test payorAdd1
    }

    /**
     * Test the property 'payorAdd2'
     */
    @Test
    public void payorAdd2Test() {
        // TODO: test payorAdd2
    }

    /**
     * Test the property 'payorCity'
     */
    @Test
    public void payorCityTest() {
        // TODO: test payorCity
    }

    /**
     * Test the property 'payorState'
     */
    @Test
    public void payorStateTest() {
        // TODO: test payorState
    }

    /**
     * Test the property 'payorZip'
     */
    @Test
    public void payorZipTest() {
        // TODO: test payorZip
    }

    /**
     * Test the property 'payeeName'
     */
    @Test
    public void payeeNameTest() {
        // TODO: test payeeName
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'net'
     */
    @Test
    public void netTest() {
        // TODO: test net
    }

    /**
     * Test the property 'gross'
     */
    @Test
    public void grossTest() {
        // TODO: test gross
    }

    /**
     * Test the property 'totalTaxes'
     */
    @Test
    public void totalTaxesTest() {
        // TODO: test totalTaxes
    }

    /**
     * Test the property 'totalDeductions'
     */
    @Test
    public void totalDeductionsTest() {
        // TODO: test totalDeductions
    }

    /**
     * Test the property 'ytdNet'
     */
    @Test
    public void ytdNetTest() {
        // TODO: test ytdNet
    }

    /**
     * Test the property 'ytdGross'
     */
    @Test
    public void ytdGrossTest() {
        // TODO: test ytdGross
    }

    /**
     * Test the property 'ytdTaxes'
     */
    @Test
    public void ytdTaxesTest() {
        // TODO: test ytdTaxes
    }

    /**
     * Test the property 'ytdDeductions'
     */
    @Test
    public void ytdDeductionsTest() {
        // TODO: test ytdDeductions
    }

    /**
     * Test the property 'fedWitholding'
     */
    @Test
    public void fedWitholdingTest() {
        // TODO: test fedWitholding
    }

    /**
     * Test the property 'federalType'
     */
    @Test
    public void federalTypeTest() {
        // TODO: test federalType
    }

    /**
     * Test the property 'twoJobs'
     */
    @Test
    public void twoJobsTest() {
        // TODO: test twoJobs
    }

    /**
     * Test the property 'dependentsAmount'
     */
    @Test
    public void dependentsAmountTest() {
        // TODO: test dependentsAmount
    }

    /**
     * Test the property 'otherIncome'
     */
    @Test
    public void otherIncomeTest() {
        // TODO: test otherIncome
    }

    /**
     * Test the property 'deductionsAmount'
     */
    @Test
    public void deductionsAmountTest() {
        // TODO: test deductionsAmount
    }

    /**
     * Test the property 'stateWithholding'
     */
    @Test
    public void stateWithholdingTest() {
        // TODO: test stateWithholding
    }

    /**
     * Test the property 'localWithholding'
     */
    @Test
    public void localWithholdingTest() {
        // TODO: test localWithholding
    }

    /**
     * Test the property 'additionalFed'
     */
    @Test
    public void additionalFedTest() {
        // TODO: test additionalFed
    }

    /**
     * Test the property 'additionalState'
     */
    @Test
    public void additionalStateTest() {
        // TODO: test additionalState
    }

    /**
     * Test the property 'additionalLocal'
     */
    @Test
    public void additionalLocalTest() {
        // TODO: test additionalLocal
    }

    /**
     * Test the property 'taxState'
     */
    @Test
    public void taxStateTest() {
        // TODO: test taxState
    }

    /**
     * Test the property 'taxLocal'
     */
    @Test
    public void taxLocalTest() {
        // TODO: test taxLocal
    }

    /**
     * Test the property 'wages'
     */
    @Test
    public void wagesTest() {
        // TODO: test wages
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

    /**
     * Test the property 'deductions'
     */
    @Test
    public void deductionsTest() {
        // TODO: test deductions
    }

    /**
     * Test the property 'deposits'
     */
    @Test
    public void depositsTest() {
        // TODO: test deposits
    }

}
