/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GoalsGetAllAggregateInfoResponsePersonsInner
 */
public class GoalsGetAllAggregateInfoResponsePersonsInnerTest {
    private final GoalsGetAllAggregateInfoResponsePersonsInner model = new GoalsGetAllAggregateInfoResponsePersonsInner();

    /**
     * Model tests for GoalsGetAllAggregateInfoResponsePersonsInner
     */
    @Test
    public void testGoalsGetAllAggregateInfoResponsePersonsInner() {
        // TODO: test GoalsGetAllAggregateInfoResponsePersonsInner
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'displayFirstName'
     */
    @Test
    public void displayFirstNameTest() {
        // TODO: test displayFirstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'photoUrl'
     */
    @Test
    public void photoUrlTest() {
        // TODO: test photoUrl
    }

}
