/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GoalsGetAllAggregateInfo200Response1FiltersInnerActions
 */
public class GoalsGetAllAggregateInfo200Response1FiltersInnerActionsTest {
    private final GoalsGetAllAggregateInfo200Response1FiltersInnerActions model = new GoalsGetAllAggregateInfo200Response1FiltersInnerActions();

    /**
     * Model tests for GoalsGetAllAggregateInfo200Response1FiltersInnerActions
     */
    @Test
    public void testGoalsGetAllAggregateInfo200Response1FiltersInnerActions() {
        // TODO: test GoalsGetAllAggregateInfo200Response1FiltersInnerActions
    }

    /**
     * Test the property 'canCloseGoal'
     */
    @Test
    public void canCloseGoalTest() {
        // TODO: test canCloseGoal
    }

    /**
     * Test the property 'canEditGoal'
     */
    @Test
    public void canEditGoalTest() {
        // TODO: test canEditGoal
    }

    /**
     * Test the property 'canEditGoalProgressBar'
     */
    @Test
    public void canEditGoalProgressBarTest() {
        // TODO: test canEditGoalProgressBar
    }

    /**
     * Test the property 'canReopenGoal'
     */
    @Test
    public void canReopenGoalTest() {
        // TODO: test canReopenGoal
    }

    /**
     * Test the property 'canShareGoal'
     */
    @Test
    public void canShareGoalTest() {
        // TODO: test canShareGoal
    }

}
