/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GoalsGetAllAggregateInfo200ResponseCommentsInner
 */
public class GoalsGetAllAggregateInfo200ResponseCommentsInnerTest {
    private final GoalsGetAllAggregateInfo200ResponseCommentsInner model = new GoalsGetAllAggregateInfo200ResponseCommentsInner();

    /**
     * Model tests for GoalsGetAllAggregateInfo200ResponseCommentsInner
     */
    @Test
    public void testGoalsGetAllAggregateInfo200ResponseCommentsInner() {
        // TODO: test GoalsGetAllAggregateInfo200ResponseCommentsInner
    }

    /**
     * Test the property 'goalId'
     */
    @Test
    public void goalIdTest() {
        // TODO: test goalId
    }

    /**
     * Test the property 'commentCount'
     */
    @Test
    public void commentCountTest() {
        // TODO: test commentCount
    }

}
