/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Milestone;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewGoal
 */
public class NewGoalTest {
    private final NewGoal model = new NewGoal();

    /**
     * Model tests for NewGoal
     */
    @Test
    public void testNewGoal() {
        // TODO: test NewGoal
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'percentComplete'
     */
    @Test
    public void percentCompleteTest() {
        // TODO: test percentComplete
    }

    /**
     * Test the property 'alignsWithOptionId'
     */
    @Test
    public void alignsWithOptionIdTest() {
        // TODO: test alignsWithOptionId
    }

    /**
     * Test the property 'sharedWithEmployeeIds'
     */
    @Test
    public void sharedWithEmployeeIdsTest() {
        // TODO: test sharedWithEmployeeIds
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'completionDate'
     */
    @Test
    public void completionDateTest() {
        // TODO: test completionDate
    }

    /**
     * Test the property 'milestones'
     */
    @Test
    public void milestonesTest() {
        // TODO: test milestones
    }

}
