/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TimeTrackingStoreDailyEntriesRequestEntriesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TimeTrackingStoreDailyEntriesRequest
 */
public class TimeTrackingStoreDailyEntriesRequestTest {
    private final TimeTrackingStoreDailyEntriesRequest model = new TimeTrackingStoreDailyEntriesRequest();

    /**
     * Model tests for TimeTrackingStoreDailyEntriesRequest
     */
    @Test
    public void testTimeTrackingStoreDailyEntriesRequest() {
        // TODO: test TimeTrackingStoreDailyEntriesRequest
    }

    /**
     * Test the property 'entries'
     */
    @Test
    public void entriesTest() {
        // TODO: test entries
    }

}
