/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TimeOffRequestDatesInner;
import com.konfigthis.client.model.TimeOffRequestNotesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TimeOffRequest
 */
public class TimeOffRequestTest {
    private final TimeOffRequest model = new TimeOffRequest();

    /**
     * Model tests for TimeOffRequest
     */
    @Test
    public void testTimeOffRequest() {
        // TODO: test TimeOffRequest
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'timeOffTypeId'
     */
    @Test
    public void timeOffTypeIdTest() {
        // TODO: test timeOffTypeId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

    /**
     * Test the property 'previousRequest'
     */
    @Test
    public void previousRequestTest() {
        // TODO: test previousRequest
    }

}
