/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TimeTrackingTask;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TimeTrackingProjectWithTasksAndEmployeeIds
 */
public class TimeTrackingProjectWithTasksAndEmployeeIdsTest {
    private final TimeTrackingProjectWithTasksAndEmployeeIds model = new TimeTrackingProjectWithTasksAndEmployeeIds();

    /**
     * Model tests for TimeTrackingProjectWithTasksAndEmployeeIds
     */
    @Test
    public void testTimeTrackingProjectWithTasksAndEmployeeIds() {
        // TODO: test TimeTrackingProjectWithTasksAndEmployeeIds
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'tasks'
     */
    @Test
    public void tasksTest() {
        // TODO: test tasks
    }

    /**
     * Test the property 'employeeIds'
     */
    @Test
    public void employeeIdsTest() {
        // TODO: test employeeIds
    }

}
