/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WebHookResponseFrequency;
import com.konfigthis.client.model.WebHookResponseLimit;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebHookResponse
 */
public class WebHookResponseTest {
    private final WebHookResponse model = new WebHookResponse();

    /**
     * Model tests for WebHookResponse
     */
    @Test
    public void testWebHookResponse() {
        // TODO: test WebHookResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'lastSent'
     */
    @Test
    public void lastSentTest() {
        // TODO: test lastSent
    }

    /**
     * Test the property 'monitorFields'
     */
    @Test
    public void monitorFieldsTest() {
        // TODO: test monitorFields
    }

    /**
     * Test the property 'postFields'
     */
    @Test
    public void postFieldsTest() {
        // TODO: test postFields
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'includeCompanyDomain'
     */
    @Test
    public void includeCompanyDomainTest() {
        // TODO: test includeCompanyDomain
    }

}
