/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BenefitGroupPlanCost
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BenefitGroupPlanCost {
  public static final String SERIALIZED_NAME_BENEFIT_GROUP_PLAN_ID = "benefitGroupPlanId";
  @SerializedName(SERIALIZED_NAME_BENEFIT_GROUP_PLAN_ID)
  private String benefitGroupPlanId;

  public static final String SERIALIZED_NAME_BENEFIT_PLAN_COVERAGE_ID = "benefitPlanCoverageId";
  @SerializedName(SERIALIZED_NAME_BENEFIT_PLAN_COVERAGE_ID)
  private String benefitPlanCoverageId;

  public static final String SERIALIZED_NAME_EMPLOYEE_COST = "employeeCost";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_COST)
  private String employeeCost;

  public static final String SERIALIZED_NAME_COMPANY_COST = "companyCost";
  @SerializedName(SERIALIZED_NAME_COMPANY_COST)
  private String companyCost;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private String startDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private String endDate;

  public BenefitGroupPlanCost() {
  }

  public BenefitGroupPlanCost benefitGroupPlanId(String benefitGroupPlanId) {
    
    
    
    
    this.benefitGroupPlanId = benefitGroupPlanId;
    return this;
  }

   /**
   * 
   * @return benefitGroupPlanId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBenefitGroupPlanId() {
    return benefitGroupPlanId;
  }


  public void setBenefitGroupPlanId(String benefitGroupPlanId) {
    
    
    
    this.benefitGroupPlanId = benefitGroupPlanId;
  }


  public BenefitGroupPlanCost benefitPlanCoverageId(String benefitPlanCoverageId) {
    
    
    
    
    this.benefitPlanCoverageId = benefitPlanCoverageId;
    return this;
  }

   /**
   * 
   * @return benefitPlanCoverageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBenefitPlanCoverageId() {
    return benefitPlanCoverageId;
  }


  public void setBenefitPlanCoverageId(String benefitPlanCoverageId) {
    
    
    
    this.benefitPlanCoverageId = benefitPlanCoverageId;
  }


  public BenefitGroupPlanCost employeeCost(String employeeCost) {
    
    
    
    
    this.employeeCost = employeeCost;
    return this;
  }

   /**
   * 
   * @return employeeCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmployeeCost() {
    return employeeCost;
  }


  public void setEmployeeCost(String employeeCost) {
    
    
    
    this.employeeCost = employeeCost;
  }


  public BenefitGroupPlanCost companyCost(String companyCost) {
    
    
    
    
    this.companyCost = companyCost;
    return this;
  }

   /**
   * 
   * @return companyCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCompanyCost() {
    return companyCost;
  }


  public void setCompanyCost(String companyCost) {
    
    
    
    this.companyCost = companyCost;
  }


  public BenefitGroupPlanCost startDate(String startDate) {
    
    
    
    
    this.startDate = startDate;
    return this;
  }

   /**
   * 
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStartDate() {
    return startDate;
  }


  public void setStartDate(String startDate) {
    
    
    
    this.startDate = startDate;
  }


  public BenefitGroupPlanCost endDate(String endDate) {
    
    
    
    
    this.endDate = endDate;
    return this;
  }

   /**
   * 
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEndDate() {
    return endDate;
  }


  public void setEndDate(String endDate) {
    
    
    
    this.endDate = endDate;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BenefitGroupPlanCost instance itself
   */
  public BenefitGroupPlanCost putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BenefitGroupPlanCost benefitGroupPlanCost = (BenefitGroupPlanCost) o;
    return Objects.equals(this.benefitGroupPlanId, benefitGroupPlanCost.benefitGroupPlanId) &&
        Objects.equals(this.benefitPlanCoverageId, benefitGroupPlanCost.benefitPlanCoverageId) &&
        Objects.equals(this.employeeCost, benefitGroupPlanCost.employeeCost) &&
        Objects.equals(this.companyCost, benefitGroupPlanCost.companyCost) &&
        Objects.equals(this.startDate, benefitGroupPlanCost.startDate) &&
        Objects.equals(this.endDate, benefitGroupPlanCost.endDate)&&
        Objects.equals(this.additionalProperties, benefitGroupPlanCost.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(benefitGroupPlanId, benefitPlanCoverageId, employeeCost, companyCost, startDate, endDate, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BenefitGroupPlanCost {\n");
    sb.append("    benefitGroupPlanId: ").append(toIndentedString(benefitGroupPlanId)).append("\n");
    sb.append("    benefitPlanCoverageId: ").append(toIndentedString(benefitPlanCoverageId)).append("\n");
    sb.append("    employeeCost: ").append(toIndentedString(employeeCost)).append("\n");
    sb.append("    companyCost: ").append(toIndentedString(companyCost)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("benefitGroupPlanId");
    openapiFields.add("benefitPlanCoverageId");
    openapiFields.add("employeeCost");
    openapiFields.add("companyCost");
    openapiFields.add("startDate");
    openapiFields.add("endDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BenefitGroupPlanCost
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BenefitGroupPlanCost.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BenefitGroupPlanCost is not found in the empty JSON string", BenefitGroupPlanCost.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("benefitGroupPlanId") != null && !jsonObj.get("benefitGroupPlanId").isJsonNull()) && !jsonObj.get("benefitGroupPlanId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `benefitGroupPlanId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("benefitGroupPlanId").toString()));
      }
      if ((jsonObj.get("benefitPlanCoverageId") != null && !jsonObj.get("benefitPlanCoverageId").isJsonNull()) && !jsonObj.get("benefitPlanCoverageId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `benefitPlanCoverageId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("benefitPlanCoverageId").toString()));
      }
      if ((jsonObj.get("employeeCost") != null && !jsonObj.get("employeeCost").isJsonNull()) && !jsonObj.get("employeeCost").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `employeeCost` to be a primitive type in the JSON string but got `%s`", jsonObj.get("employeeCost").toString()));
      }
      if ((jsonObj.get("companyCost") != null && !jsonObj.get("companyCost").isJsonNull()) && !jsonObj.get("companyCost").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyCost` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyCost").toString()));
      }
      if ((jsonObj.get("startDate") != null && !jsonObj.get("startDate").isJsonNull()) && !jsonObj.get("startDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `startDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startDate").toString()));
      }
      if ((jsonObj.get("endDate") != null && !jsonObj.get("endDate").isJsonNull()) && !jsonObj.get("endDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endDate").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BenefitGroupPlanCost.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BenefitGroupPlanCost' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BenefitGroupPlanCost> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BenefitGroupPlanCost.class));

       return (TypeAdapter<T>) new TypeAdapter<BenefitGroupPlanCost>() {
           @Override
           public void write(JsonWriter out, BenefitGroupPlanCost value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BenefitGroupPlanCost read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BenefitGroupPlanCost instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BenefitGroupPlanCost given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BenefitGroupPlanCost
  * @throws IOException if the JSON string is invalid with respect to BenefitGroupPlanCost
  */
  public static BenefitGroupPlanCost fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BenefitGroupPlanCost.class);
  }

 /**
  * Convert an instance of BenefitGroupPlanCost to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

