/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner;
import com.konfigthis.client.model.GoalsGetGoalAggregateInfoResponseCommentsInner;
import com.konfigthis.client.model.GoalsGetGoalAggregateInfoResponseGoal;
import com.konfigthis.client.model.GoalsGetGoalAggregateInfoResponsePersonsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * GoalsGetGoalAggregateInfoResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GoalsGetGoalAggregateInfoResponse {
  public static final String SERIALIZED_NAME_GOAL = "goal";
  @SerializedName(SERIALIZED_NAME_GOAL)
  private GoalsGetGoalAggregateInfoResponseGoal goal;

  public static final String SERIALIZED_NAME_CAN_ALIGN = "canAlign";
  @SerializedName(SERIALIZED_NAME_CAN_ALIGN)
  private Boolean canAlign;

  public static final String SERIALIZED_NAME_CAN_CREATE_GOALS = "canCreateGoals";
  @SerializedName(SERIALIZED_NAME_CAN_CREATE_GOALS)
  private Boolean canCreateGoals;

  public static final String SERIALIZED_NAME_ALIGNS_WITH_OPTIONS = "alignsWithOptions";
  @SerializedName(SERIALIZED_NAME_ALIGNS_WITH_OPTIONS)
  private List<GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner> alignsWithOptions = null;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private List<GoalsGetGoalAggregateInfoResponseCommentsInner> comments = null;

  public static final String SERIALIZED_NAME_PERSONS = "persons";
  @SerializedName(SERIALIZED_NAME_PERSONS)
  private List<GoalsGetGoalAggregateInfoResponsePersonsInner> persons = null;

  public GoalsGetGoalAggregateInfoResponse() {
  }

  public GoalsGetGoalAggregateInfoResponse goal(GoalsGetGoalAggregateInfoResponseGoal goal) {
    
    
    
    
    this.goal = goal;
    return this;
  }

   /**
   * Get goal
   * @return goal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GoalsGetGoalAggregateInfoResponseGoal getGoal() {
    return goal;
  }


  public void setGoal(GoalsGetGoalAggregateInfoResponseGoal goal) {
    
    
    
    this.goal = goal;
  }


  public GoalsGetGoalAggregateInfoResponse canAlign(Boolean canAlign) {
    
    
    
    
    this.canAlign = canAlign;
    return this;
  }

   /**
   * The selected user can align goals with other users.
   * @return canAlign
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "The selected user can align goals with other users.")

  public Boolean getCanAlign() {
    return canAlign;
  }


  public void setCanAlign(Boolean canAlign) {
    
    
    
    this.canAlign = canAlign;
  }


  public GoalsGetGoalAggregateInfoResponse canCreateGoals(Boolean canCreateGoals) {
    
    
    
    
    this.canCreateGoals = canCreateGoals;
    return this;
  }

   /**
   * The selected user can create a goal.
   * @return canCreateGoals
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "The selected user can create a goal.")

  public Boolean getCanCreateGoals() {
    return canCreateGoals;
  }


  public void setCanCreateGoals(Boolean canCreateGoals) {
    
    
    
    this.canCreateGoals = canCreateGoals;
  }


  public GoalsGetGoalAggregateInfoResponse alignsWithOptions(List<GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner> alignsWithOptions) {
    
    
    
    
    this.alignsWithOptions = alignsWithOptions;
    return this;
  }

  public GoalsGetGoalAggregateInfoResponse addAlignsWithOptionsItem(GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner alignsWithOptionsItem) {
    if (this.alignsWithOptions == null) {
      this.alignsWithOptions = new ArrayList<>();
    }
    this.alignsWithOptions.add(alignsWithOptionsItem);
    return this;
  }

   /**
   * All possible goals that this goal could be aligned with.
   * @return alignsWithOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "All possible goals that this goal could be aligned with.")

  public List<GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner> getAlignsWithOptions() {
    return alignsWithOptions;
  }


  public void setAlignsWithOptions(List<GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner> alignsWithOptions) {
    
    
    
    this.alignsWithOptions = alignsWithOptions;
  }


  public GoalsGetGoalAggregateInfoResponse comments(List<GoalsGetGoalAggregateInfoResponseCommentsInner> comments) {
    
    
    
    
    this.comments = comments;
    return this;
  }

  public GoalsGetGoalAggregateInfoResponse addCommentsItem(GoalsGetGoalAggregateInfoResponseCommentsInner commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<>();
    }
    this.comments.add(commentsItem);
    return this;
  }

   /**
   * Comments linked to selected goal.
   * @return comments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Comments linked to selected goal.")

  public List<GoalsGetGoalAggregateInfoResponseCommentsInner> getComments() {
    return comments;
  }


  public void setComments(List<GoalsGetGoalAggregateInfoResponseCommentsInner> comments) {
    
    
    
    this.comments = comments;
  }


  public GoalsGetGoalAggregateInfoResponse persons(List<GoalsGetGoalAggregateInfoResponsePersonsInner> persons) {
    
    
    
    
    this.persons = persons;
    return this;
  }

  public GoalsGetGoalAggregateInfoResponse addPersonsItem(GoalsGetGoalAggregateInfoResponsePersonsInner personsItem) {
    if (this.persons == null) {
      this.persons = new ArrayList<>();
    }
    this.persons.add(personsItem);
    return this;
  }

   /**
   * A list of people with access to the goal.
   * @return persons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of people with access to the goal.")

  public List<GoalsGetGoalAggregateInfoResponsePersonsInner> getPersons() {
    return persons;
  }


  public void setPersons(List<GoalsGetGoalAggregateInfoResponsePersonsInner> persons) {
    
    
    
    this.persons = persons;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GoalsGetGoalAggregateInfoResponse instance itself
   */
  public GoalsGetGoalAggregateInfoResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoalsGetGoalAggregateInfoResponse goalsGetGoalAggregateInfoResponse = (GoalsGetGoalAggregateInfoResponse) o;
    return Objects.equals(this.goal, goalsGetGoalAggregateInfoResponse.goal) &&
        Objects.equals(this.canAlign, goalsGetGoalAggregateInfoResponse.canAlign) &&
        Objects.equals(this.canCreateGoals, goalsGetGoalAggregateInfoResponse.canCreateGoals) &&
        Objects.equals(this.alignsWithOptions, goalsGetGoalAggregateInfoResponse.alignsWithOptions) &&
        Objects.equals(this.comments, goalsGetGoalAggregateInfoResponse.comments) &&
        Objects.equals(this.persons, goalsGetGoalAggregateInfoResponse.persons)&&
        Objects.equals(this.additionalProperties, goalsGetGoalAggregateInfoResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goal, canAlign, canCreateGoals, alignsWithOptions, comments, persons, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoalsGetGoalAggregateInfoResponse {\n");
    sb.append("    goal: ").append(toIndentedString(goal)).append("\n");
    sb.append("    canAlign: ").append(toIndentedString(canAlign)).append("\n");
    sb.append("    canCreateGoals: ").append(toIndentedString(canCreateGoals)).append("\n");
    sb.append("    alignsWithOptions: ").append(toIndentedString(alignsWithOptions)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    persons: ").append(toIndentedString(persons)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("goal");
    openapiFields.add("canAlign");
    openapiFields.add("canCreateGoals");
    openapiFields.add("alignsWithOptions");
    openapiFields.add("comments");
    openapiFields.add("persons");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GoalsGetGoalAggregateInfoResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GoalsGetGoalAggregateInfoResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoalsGetGoalAggregateInfoResponse is not found in the empty JSON string", GoalsGetGoalAggregateInfoResponse.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `goal`
      if (jsonObj.get("goal") != null && !jsonObj.get("goal").isJsonNull()) {
        GoalsGetGoalAggregateInfoResponseGoal.validateJsonObject(jsonObj.getAsJsonObject("goal"));
      }
      if (jsonObj.get("alignsWithOptions") != null && !jsonObj.get("alignsWithOptions").isJsonNull()) {
        JsonArray jsonArrayalignsWithOptions = jsonObj.getAsJsonArray("alignsWithOptions");
        if (jsonArrayalignsWithOptions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("alignsWithOptions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `alignsWithOptions` to be an array in the JSON string but got `%s`", jsonObj.get("alignsWithOptions").toString()));
          }

          // validate the optional field `alignsWithOptions` (array)
          for (int i = 0; i < jsonArrayalignsWithOptions.size(); i++) {
            GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner.validateJsonObject(jsonArrayalignsWithOptions.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonNull()) {
        JsonArray jsonArraycomments = jsonObj.getAsJsonArray("comments");
        if (jsonArraycomments != null) {
          // ensure the json data is an array
          if (!jsonObj.get("comments").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `comments` to be an array in the JSON string but got `%s`", jsonObj.get("comments").toString()));
          }

          // validate the optional field `comments` (array)
          for (int i = 0; i < jsonArraycomments.size(); i++) {
            GoalsGetGoalAggregateInfoResponseCommentsInner.validateJsonObject(jsonArraycomments.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("persons") != null && !jsonObj.get("persons").isJsonNull()) {
        JsonArray jsonArraypersons = jsonObj.getAsJsonArray("persons");
        if (jsonArraypersons != null) {
          // ensure the json data is an array
          if (!jsonObj.get("persons").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `persons` to be an array in the JSON string but got `%s`", jsonObj.get("persons").toString()));
          }

          // validate the optional field `persons` (array)
          for (int i = 0; i < jsonArraypersons.size(); i++) {
            GoalsGetGoalAggregateInfoResponsePersonsInner.validateJsonObject(jsonArraypersons.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoalsGetGoalAggregateInfoResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoalsGetGoalAggregateInfoResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoalsGetGoalAggregateInfoResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoalsGetGoalAggregateInfoResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GoalsGetGoalAggregateInfoResponse>() {
           @Override
           public void write(JsonWriter out, GoalsGetGoalAggregateInfoResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GoalsGetGoalAggregateInfoResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GoalsGetGoalAggregateInfoResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GoalsGetGoalAggregateInfoResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GoalsGetGoalAggregateInfoResponse
  * @throws IOException if the JSON string is invalid with respect to GoalsGetGoalAggregateInfoResponse
  */
  public static GoalsGetGoalAggregateInfoResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoalsGetGoalAggregateInfoResponse.class);
  }

 /**
  * Convert an instance of GoalsGetGoalAggregateInfoResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

