/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TimeTrackingApproveEmployeeTimesheetsRequest1ClockOutsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TimeTrackingApproveEmployeeTimesheetsRequest1
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TimeTrackingApproveEmployeeTimesheetsRequest1 {
  public static final String SERIALIZED_NAME_CLOCK_OUTS = "clockOuts";
  @SerializedName(SERIALIZED_NAME_CLOCK_OUTS)
  private List<TimeTrackingApproveEmployeeTimesheetsRequest1ClockOutsInner> clockOuts = null;

  public TimeTrackingApproveEmployeeTimesheetsRequest1() {
  }

  public TimeTrackingApproveEmployeeTimesheetsRequest1 clockOuts(List<TimeTrackingApproveEmployeeTimesheetsRequest1ClockOutsInner> clockOuts) {
    
    
    
    
    this.clockOuts = clockOuts;
    return this;
  }

  public TimeTrackingApproveEmployeeTimesheetsRequest1 addClockOutsItem(TimeTrackingApproveEmployeeTimesheetsRequest1ClockOutsInner clockOutsItem) {
    if (this.clockOuts == null) {
      this.clockOuts = new ArrayList<>();
    }
    this.clockOuts.add(clockOutsItem);
    return this;
  }

   /**
   * Array of clock out information
   * @return clockOuts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Array of clock out information")

  public List<TimeTrackingApproveEmployeeTimesheetsRequest1ClockOutsInner> getClockOuts() {
    return clockOuts;
  }


  public void setClockOuts(List<TimeTrackingApproveEmployeeTimesheetsRequest1ClockOutsInner> clockOuts) {
    
    
    
    this.clockOuts = clockOuts;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TimeTrackingApproveEmployeeTimesheetsRequest1 instance itself
   */
  public TimeTrackingApproveEmployeeTimesheetsRequest1 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTrackingApproveEmployeeTimesheetsRequest1 timeTrackingApproveEmployeeTimesheetsRequest1 = (TimeTrackingApproveEmployeeTimesheetsRequest1) o;
    return Objects.equals(this.clockOuts, timeTrackingApproveEmployeeTimesheetsRequest1.clockOuts)&&
        Objects.equals(this.additionalProperties, timeTrackingApproveEmployeeTimesheetsRequest1.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clockOuts, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTrackingApproveEmployeeTimesheetsRequest1 {\n");
    sb.append("    clockOuts: ").append(toIndentedString(clockOuts)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("clockOuts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TimeTrackingApproveEmployeeTimesheetsRequest1
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TimeTrackingApproveEmployeeTimesheetsRequest1.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TimeTrackingApproveEmployeeTimesheetsRequest1 is not found in the empty JSON string", TimeTrackingApproveEmployeeTimesheetsRequest1.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("clockOuts") != null && !jsonObj.get("clockOuts").isJsonNull()) {
        JsonArray jsonArrayclockOuts = jsonObj.getAsJsonArray("clockOuts");
        if (jsonArrayclockOuts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("clockOuts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `clockOuts` to be an array in the JSON string but got `%s`", jsonObj.get("clockOuts").toString()));
          }

          // validate the optional field `clockOuts` (array)
          for (int i = 0; i < jsonArrayclockOuts.size(); i++) {
            TimeTrackingApproveEmployeeTimesheetsRequest1ClockOutsInner.validateJsonObject(jsonArrayclockOuts.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TimeTrackingApproveEmployeeTimesheetsRequest1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TimeTrackingApproveEmployeeTimesheetsRequest1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TimeTrackingApproveEmployeeTimesheetsRequest1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TimeTrackingApproveEmployeeTimesheetsRequest1.class));

       return (TypeAdapter<T>) new TypeAdapter<TimeTrackingApproveEmployeeTimesheetsRequest1>() {
           @Override
           public void write(JsonWriter out, TimeTrackingApproveEmployeeTimesheetsRequest1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TimeTrackingApproveEmployeeTimesheetsRequest1 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TimeTrackingApproveEmployeeTimesheetsRequest1 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TimeTrackingApproveEmployeeTimesheetsRequest1 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TimeTrackingApproveEmployeeTimesheetsRequest1
  * @throws IOException if the JSON string is invalid with respect to TimeTrackingApproveEmployeeTimesheetsRequest1
  */
  public static TimeTrackingApproveEmployeeTimesheetsRequest1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TimeTrackingApproveEmployeeTimesheetsRequest1.class);
  }

 /**
  * Convert an instance of TimeTrackingApproveEmployeeTimesheetsRequest1 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

