/*
 * BambooHR API
 * This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TrainingTypeAdditionRequestCategory;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TrainingTypeAdditionRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TrainingTypeAdditionRequest {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  @SerializedName(SERIALIZED_NAME_FREQUENCY)
  private Integer frequency;

  public static final String SERIALIZED_NAME_RENEWABLE = "renewable";
  @SerializedName(SERIALIZED_NAME_RENEWABLE)
  private Boolean renewable;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private TrainingTypeAdditionRequestCategory category;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  @SerializedName(SERIALIZED_NAME_REQUIRED)
  private Boolean required;

  public static final String SERIALIZED_NAME_DUE_FROM_HIRE_DATE = "dueFromHireDate";
  @SerializedName(SERIALIZED_NAME_DUE_FROM_HIRE_DATE)
  private Integer dueFromHireDate;

  public static final String SERIALIZED_NAME_LINK_URL = "linkUrl";
  @SerializedName(SERIALIZED_NAME_LINK_URL)
  private String linkUrl;

  public static final String SERIALIZED_NAME_ALLOW_EMPLOYEES_TO_MARK_COMPLETE = "allowEmployeesToMarkComplete";
  @SerializedName(SERIALIZED_NAME_ALLOW_EMPLOYEES_TO_MARK_COMPLETE)
  private Boolean allowEmployeesToMarkComplete = false;

  public TrainingTypeAdditionRequest() {
  }

  public TrainingTypeAdditionRequest description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Description for the training.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description for the training.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public TrainingTypeAdditionRequest name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Name of the new training type.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "My New Training", required = true, value = "Name of the new training type.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public TrainingTypeAdditionRequest frequency(Integer frequency) {
    
    
    
    
    this.frequency = frequency;
    return this;
  }

   /**
   * The frequency is the (optional) amount of months between renewing trainings. Not valid if training are not renewable.
   * @return frequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12", value = "The frequency is the (optional) amount of months between renewing trainings. Not valid if training are not renewable.")

  public Integer getFrequency() {
    return frequency;
  }


  public void setFrequency(Integer frequency) {
    
    
    
    this.frequency = frequency;
  }


  public TrainingTypeAdditionRequest renewable(Boolean renewable) {
    
    
    
    
    this.renewable = renewable;
    return this;
  }

   /**
   * Renewable is optional but if you are setting it to true you must pass a frequency which is the months between renewals.
   * @return renewable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Renewable is optional but if you are setting it to true you must pass a frequency which is the months between renewals.")

  public Boolean getRenewable() {
    return renewable;
  }


  public void setRenewable(Boolean renewable) {
    
    
    
    this.renewable = renewable;
  }


  public TrainingTypeAdditionRequest category(TrainingTypeAdditionRequestCategory category) {
    
    
    
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TrainingTypeAdditionRequestCategory getCategory() {
    return category;
  }


  public void setCategory(TrainingTypeAdditionRequestCategory category) {
    
    
    
    this.category = category;
  }


  public TrainingTypeAdditionRequest required(Boolean required) {
    
    
    
    
    this.required = required;
    return this;
  }

   /**
   * Is this a required training?
   * @return required
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "false", required = true, value = "Is this a required training?")

  public Boolean getRequired() {
    return required;
  }


  public void setRequired(Boolean required) {
    
    
    
    this.required = required;
  }


  public TrainingTypeAdditionRequest dueFromHireDate(Integer dueFromHireDate) {
    
    
    
    
    this.dueFromHireDate = dueFromHireDate;
    return this;
  }

   /**
   * Number of days before the training is due for new hires. Not valid unless training is required.
   * @return dueFromHireDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "30", value = "Number of days before the training is due for new hires. Not valid unless training is required.")

  public Integer getDueFromHireDate() {
    return dueFromHireDate;
  }


  public void setDueFromHireDate(Integer dueFromHireDate) {
    
    
    
    this.dueFromHireDate = dueFromHireDate;
  }


  public TrainingTypeAdditionRequest linkUrl(String linkUrl) {
    
    
    
    
    this.linkUrl = linkUrl;
    return this;
  }

   /**
   * Optional URL that can be included with a training.
   * @return linkUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional URL that can be included with a training.")

  public String getLinkUrl() {
    return linkUrl;
  }


  public void setLinkUrl(String linkUrl) {
    
    
    
    this.linkUrl = linkUrl;
  }


  public TrainingTypeAdditionRequest allowEmployeesToMarkComplete(Boolean allowEmployeesToMarkComplete) {
    
    
    
    
    this.allowEmployeesToMarkComplete = allowEmployeesToMarkComplete;
    return this;
  }

   /**
   * Allows all employees who can view the training to be able to mark it complete.
   * @return allowEmployeesToMarkComplete
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Allows all employees who can view the training to be able to mark it complete.")

  public Boolean getAllowEmployeesToMarkComplete() {
    return allowEmployeesToMarkComplete;
  }


  public void setAllowEmployeesToMarkComplete(Boolean allowEmployeesToMarkComplete) {
    
    
    
    this.allowEmployeesToMarkComplete = allowEmployeesToMarkComplete;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TrainingTypeAdditionRequest instance itself
   */
  public TrainingTypeAdditionRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainingTypeAdditionRequest trainingTypeAdditionRequest = (TrainingTypeAdditionRequest) o;
    return Objects.equals(this.description, trainingTypeAdditionRequest.description) &&
        Objects.equals(this.name, trainingTypeAdditionRequest.name) &&
        Objects.equals(this.frequency, trainingTypeAdditionRequest.frequency) &&
        Objects.equals(this.renewable, trainingTypeAdditionRequest.renewable) &&
        Objects.equals(this.category, trainingTypeAdditionRequest.category) &&
        Objects.equals(this.required, trainingTypeAdditionRequest.required) &&
        Objects.equals(this.dueFromHireDate, trainingTypeAdditionRequest.dueFromHireDate) &&
        Objects.equals(this.linkUrl, trainingTypeAdditionRequest.linkUrl) &&
        Objects.equals(this.allowEmployeesToMarkComplete, trainingTypeAdditionRequest.allowEmployeesToMarkComplete)&&
        Objects.equals(this.additionalProperties, trainingTypeAdditionRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, frequency, renewable, category, required, dueFromHireDate, linkUrl, allowEmployeesToMarkComplete, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainingTypeAdditionRequest {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    renewable: ").append(toIndentedString(renewable)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    dueFromHireDate: ").append(toIndentedString(dueFromHireDate)).append("\n");
    sb.append("    linkUrl: ").append(toIndentedString(linkUrl)).append("\n");
    sb.append("    allowEmployeesToMarkComplete: ").append(toIndentedString(allowEmployeesToMarkComplete)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("name");
    openapiFields.add("frequency");
    openapiFields.add("renewable");
    openapiFields.add("category");
    openapiFields.add("required");
    openapiFields.add("dueFromHireDate");
    openapiFields.add("linkUrl");
    openapiFields.add("allowEmployeesToMarkComplete");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("required");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TrainingTypeAdditionRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TrainingTypeAdditionRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TrainingTypeAdditionRequest is not found in the empty JSON string", TrainingTypeAdditionRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TrainingTypeAdditionRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `category`
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
        TrainingTypeAdditionRequestCategory.validateJsonObject(jsonObj.getAsJsonObject("category"));
      }
      if ((jsonObj.get("linkUrl") != null && !jsonObj.get("linkUrl").isJsonNull()) && !jsonObj.get("linkUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `linkUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("linkUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TrainingTypeAdditionRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TrainingTypeAdditionRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TrainingTypeAdditionRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TrainingTypeAdditionRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TrainingTypeAdditionRequest>() {
           @Override
           public void write(JsonWriter out, TrainingTypeAdditionRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TrainingTypeAdditionRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TrainingTypeAdditionRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TrainingTypeAdditionRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TrainingTypeAdditionRequest
  * @throws IOException if the JSON string is invalid with respect to TrainingTypeAdditionRequest
  */
  public static TrainingTypeAdditionRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TrainingTypeAdditionRequest.class);
  }

 /**
  * Convert an instance of TrainingTypeAdditionRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

